### ISSUE TITLE
Add Validations to the AddOrder Form

### ISSUE THREAD

**Issue by rasikraj01** [rasikraj01/mybiz#18]

**Comment by pranay414** [comment]
I would like to take it up.

**Comment by rasikraj01** [comment]
@pranay414 👍 sure

**Comment by pranay414** [comment]
Also what kind of validation you expect?

**Comment by rasikraj01** [comment]
Just the basic form validation 
- empty strings should be rejected
- description shouldn't be more than 500 characters
- dueDate shouldn't be before the orderDate
