### ISSUE TITLE
Update the UI of Customers Page

### ISSUE THREAD

**Issue by rasikraj01** [rasikraj01/mybiz#19]
Add a screenshot of the changes in the comments when making a PR.

**Comment by shantiswarup** [comment]
Can I work on this ? What kind changes in UI required ?

**Comment by Shadmanwaris** [comment]
Please review PR #1

**Comment by shantiswarup** [comment]
![customer_view](https://user-images.githubusercontent.com/10672879/47691385-d9215900-dc17-11e8-92be-efca0de19c24.png)
![customer_edit](https://user-images.githubusercontent.com/10672879/47691386-d9b9ef80-dc17-11e8-848a-852fd6660cfa.png)
![customer_add](https://user-images.githubusercontent.com/10672879/47691387-da528600-dc17-11e8-82f6-157c72c6cc66.png)


Please review PR 23
